mybatis:
  mapper-locations: classpath:mapping/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zzWeb?characterEncoding=UTF-8&useUnicode=true&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
server:
  session:
    timeout: 7200
